<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('countries')->truncate();
        DB::table('countries')->insert([[

            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "BD", "Name" => "Bangladesh", "Iso3" => "BGD", "Unicode" => "🇧🇩", "Dial" => "880", "currency_id" => "BDT", "Capital" => "Dhaka", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "BE", "Name" => "Belgium", "Iso3" => "BEL", "Unicode" => "🇧🇪", "Dial" => "32", "currency_id" => "EUR", "Capital" => "Brussels", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "BF", "Name" => "Burkina Faso", "Iso3" => "BFA", "Unicode" => "🇧🇫", "Dial" => "226", "currency_id" => "XOF", "Capital" => "Ouagadougou", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "BG", "Name" => "Bulgaria", "Iso3" => "BGR", "Unicode" => "🇧🇬", "Dial" => "359", "currency_id" => "BGN", "Capital" => "Sofia", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "BA", "Name" => "Bosnia and Herzegovina", "Iso3" => "BIH", "Unicode" => "🇧🇦", "Dial" => "387", "currency_id" => "BAM", "Capital" => "Sarajevo", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "BB", "Name" => "Barbados", "Iso3" => "BRB", "Unicode" => "🇧🇧", "Dial" => "+1-246", "currency_id" => "BBD", "Capital" => "Bridgetown", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "WF", "Name" => "Wallis and Futuna", "Iso3" => "WLF", "Unicode" => "🇼🇫", "Dial" => "681", "currency_id" => "XPF", "Capital" => "Mata Utu", "Continent" => "OC"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "BL", "Name" => "Saint Barthelemy", "Iso3" => "BLM", "Unicode" => "🇧🇱", "Dial" => "590", "currency_id" => "EUR", "Capital" => "Gustavia", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "BM", "Name" => "Bermuda", "Iso3" => "BMU", "Unicode" => "🇧🇲", "Dial" => "+1-441", "currency_id" => "BMD", "Capital" => "Hamilton", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "BN", "Name" => "Brunei", "Iso3" => "BRN", "Unicode" => "🇧🇳", "Dial" => "673", "currency_id" => "BND", "Capital" => "Bandar Seri Begawan", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "BO", "Name" => "Bolivia", "Iso3" => "BOL", "Unicode" => "🇧🇴", "Dial" => "591", "currency_id" => "BOB", "Capital" => "Sucre", "Continent" => "SA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "BH", "Name" => "Bahrain", "Iso3" => "BHR", "Unicode" => "🇧🇭", "Dial" => "973", "currency_id" => "BHD", "Capital" => "Manama", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "BI", "Name" => "Burundi", "Iso3" => "BDI", "Unicode" => "🇧🇮", "Dial" => "257", "currency_id" => "BIF", "Capital" => "Bujumbura", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "BJ", "Name" => "Benin", "Iso3" => "BEN", "Unicode" => "🇧🇯", "Dial" => "229", "currency_id" => "XOF", "Capital" => "Porto-Novo", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "BT", "Name" => "Bhutan", "Iso3" => "BTN", "Unicode" => "🇧🇹", "Dial" => "975", "currency_id" => "BTN", "Capital" => "Thimphu", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "JM", "Name" => "Jamaica", "Iso3" => "JAM", "Unicode" => "🇯🇲", "Dial" => "+1-876", "currency_id" => "JMD", "Capital" => "Kingston", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "BV", "Name" => "Bouvet Island", "Iso3" => "BVT", "Unicode" => "🇧🇻", "Dial" => "", "currency_id" => "NOK", "Capital" => "", "Continent" => "AN"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "BW", "Name" => "Botswana", "Iso3" => "BWA", "Unicode" => "🇧🇼", "Dial" => "267", "currency_id" => "BWP", "Capital" => "Gaborone", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "WS", "Name" => "Samoa", "Iso3" => "WSM", "Unicode" => "🇼🇸", "Dial" => "685", "currency_id" => "WST", "Capital" => "Apia", "Continent" => "OC"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "BQ", "Name" => "Bonaire, Saint Eustatius and Saba ", "Iso3" => "BES", "Unicode" => "🇧🇶", "Dial" => "599", "currency_id" => "USD", "Capital" => "", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "BR", "Name" => "Brazil", "Iso3" => "BRA", "Unicode" => "🇧🇷", "Dial" => "55", "currency_id" => "BRL", "Capital" => "Brasilia", "Continent" => "SA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "BS", "Name" => "Bahamas", "Iso3" => "BHS", "Unicode" => "🇧🇸", "Dial" => "+1-242", "currency_id" => "BSD", "Capital" => "Nassau", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "JE", "Name" => "Jersey", "Iso3" => "JEY", "Unicode" => "🇯🇪", "Dial" => "+44-1534", "currency_id" => "GBP", "Capital" => "Saint Helier", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "BY", "Name" => "Belarus", "Iso3" => "BLR", "Unicode" => "🇧🇾", "Dial" => "375", "currency_id" => "BYR", "Capital" => "Minsk", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "BZ", "Name" => "Belize", "Iso3" => "BLZ", "Unicode" => "🇧🇿", "Dial" => "501", "currency_id" => "BZD", "Capital" => "Belmopan", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "RU", "Name" => "Russia", "Iso3" => "RUS", "Unicode" => "🇷🇺", "Dial" => "7", "currency_id" => "RUB", "Capital" => "Moscow", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "RW", "Name" => "Rwanda", "Iso3" => "RWA", "Unicode" => "🇷🇼", "Dial" => "250", "currency_id" => "RWF", "Capital" => "Kigali", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "RS", "Name" => "Serbia", "Iso3" => "SRB", "Unicode" => "🇷🇸", "Dial" => "381", "currency_id" => "RSD", "Capital" => "Belgrade", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "TL", "Name" => "East Timor", "Iso3" => "TLS", "Unicode" => "🇹🇱", "Dial" => "670", "currency_id" => "USD", "Capital" => "Dili", "Continent" => "OC"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "RE", "Name" => "Reunion", "Iso3" => "REU", "Unicode" => "🇷🇪", "Dial" => "262", "currency_id" => "EUR", "Capital" => "Saint-Denis", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "TM", "Name" => "Turkmenistan", "Iso3" => "TKM", "Unicode" => "🇹🇲", "Dial" => "993", "currency_id" => "TMT", "Capital" => "Ashgabat", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "TJ", "Name" => "Tajikistan", "Iso3" => "TJK", "Unicode" => "🇹🇯", "Dial" => "992", "currency_id" => "TJS", "Capital" => "Dushanbe", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "RO", "Name" => "Romania", "Iso3" => "ROU", "Unicode" => "🇷🇴", "Dial" => "40", "currency_id" => "RON", "Capital" => "Bucharest", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "TK", "Name" => "Tokelau", "Iso3" => "TKL", "Unicode" => "🇹🇰", "Dial" => "690", "currency_id" => "NZD", "Capital" => "", "Continent" => "OC"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "GW", "Name" => "Guinea-Bissau", "Iso3" => "GNB", "Unicode" => "🇬🇼", "Dial" => "245", "currency_id" => "XOF", "Capital" => "Bissau", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "GU", "Name" => "Guam", "Iso3" => "GUM", "Unicode" => "🇬🇺", "Dial" => "+1-671", "currency_id" => "USD", "Capital" => "Hagatna", "Continent" => "OC"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "GT", "Name" => "Guatemala", "Iso3" => "GTM", "Unicode" => "🇬🇹", "Dial" => "502", "currency_id" => "GTQ", "Capital" => "Guatemala City", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "GS", "Name" => "South Georgia and the South Sandwich Islands", "Iso3" => "SGS", "Unicode" => "🇬🇸", "Dial" => "", "currency_id" => "GBP", "Capital" => "Grytviken", "Continent" => "AN"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "GR", "Name" => "Greece", "Iso3" => "GRC", "Unicode" => "🇬🇷", "Dial" => "30", "currency_id" => "EUR", "Capital" => "Athens", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "GQ", "Name" => "Equatorial Guinea", "Iso3" => "GNQ", "Unicode" => "🇬🇶", "Dial" => "240", "currency_id" => "XAF", "Capital" => "Malabo", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "GP", "Name" => "Guadeloupe", "Iso3" => "GLP", "Unicode" => "🇬🇵", "Dial" => "590", "currency_id" => "EUR", "Capital" => "Basse-Terre", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "JP", "Name" => "Japan", "Iso3" => "JPN", "Unicode" => "🇯🇵", "Dial" => "81", "currency_id" => "JPY", "Capital" => "Tokyo", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "GY", "Name" => "Guyana", "Iso3" => "GUY", "Unicode" => "🇬🇾", "Dial" => "592", "currency_id" => "GYD", "Capital" => "Georgetown", "Continent" => "SA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "GG", "Name" => "Guernsey", "Iso3" => "GGY", "Unicode" => "🇬🇬", "Dial" => "+44-1481", "currency_id" => "GBP", "Capital" => "St Peter Port", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "GF", "Name" => "French Guiana", "Iso3" => "GUF", "Unicode" => "🇬🇫", "Dial" => "594", "currency_id" => "EUR", "Capital" => "Cayenne", "Continent" => "SA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "GE", "Name" => "Georgia", "Iso3" => "GEO", "Unicode" => "🇬🇪", "Dial" => "995", "currency_id" => "GEL", "Capital" => "Tbilisi", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "GD", "Name" => "Grenada", "Iso3" => "GRD", "Unicode" => "🇬🇩", "Dial" => "+1-473", "currency_id" => "XCD", "Capital" => "St. George's", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "GB", "Name" => "United Kingdom", "Iso3" => "GBR", "Unicode" => "🇬🇧", "Dial" => "44", "currency_id" => "GBP", "Capital" => "London", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "GA", "Name" => "Gabon", "Iso3" => "GAB", "Unicode" => "🇬🇦", "Dial" => "241", "currency_id" => "XAF", "Capital" => "Libreville", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "SV", "Name" => "El Salvador", "Iso3" => "SLV", "Unicode" => "🇸🇻", "Dial" => "503", "currency_id" => "USD", "Capital" => "San Salvador", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "GN", "Name" => "Guinea", "Iso3" => "GIN", "Unicode" => "🇬🇳", "Dial" => "224", "currency_id" => "GNF", "Capital" => "Conakry", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "GM", "Name" => "Gambia", "Iso3" => "GMB", "Unicode" => "🇬🇲", "Dial" => "220", "currency_id" => "GMD", "Capital" => "Banjul", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "GL", "Name" => "Greenland", "Iso3" => "GRL", "Unicode" => "🇬🇱", "Dial" => "299", "currency_id" => "DKK", "Capital" => "Nuuk", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "GI", "Name" => "Gibraltar", "Iso3" => "GIB", "Unicode" => "🇬🇮", "Dial" => "350", "currency_id" => "GIP", "Capital" => "Gibraltar", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "GH", "Name" => "Ghana", "Iso3" => "GHA", "Unicode" => "🇬🇭", "Dial" => "233", "currency_id" => "GHS", "Capital" => "Accra", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "OM", "Name" => "Oman", "Iso3" => "OMN", "Unicode" => "🇴🇲", "Dial" => "968", "currency_id" => "OMR", "Capital" => "Muscat", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "TN", "Name" => "Tunisia", "Iso3" => "TUN", "Unicode" => "🇹🇳", "Dial" => "216", "currency_id" => "TND", "Capital" => "Tunis", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "JO", "Name" => "Jordan", "Iso3" => "JOR", "Unicode" => "🇯🇴", "Dial" => "962", "currency_id" => "JOD", "Capital" => "Amman", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "HR", "Name" => "Croatia", "Iso3" => "HRV", "Unicode" => "🇭🇷", "Dial" => "385", "currency_id" => "HRK", "Capital" => "Zagreb", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "HT", "Name" => "Haiti", "Iso3" => "HTI", "Unicode" => "🇭🇹", "Dial" => "509", "currency_id" => "HTG", "Capital" => "Port-au-Prince", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "HU", "Name" => "Hungary", "Iso3" => "HUN", "Unicode" => "🇭🇺", "Dial" => "36", "currency_id" => "HUF", "Capital" => "Budapest", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "HK", "Name" => "Hong Kong", "Iso3" => "HKG", "Unicode" => "🇭🇰", "Dial" => "852", "currency_id" => "HKD", "Capital" => "Hong Kong", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "HN", "Name" => "Honduras", "Iso3" => "HND", "Unicode" => "🇭🇳", "Dial" => "504", "currency_id" => "HNL", "Capital" => "Tegucigalpa", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "HM", "Name" => "Heard Island and McDonald Islands", "Iso3" => "HMD", "Unicode" => "🇭🇲", "Dial" => " ", "currency_id" => "AUD", "Capital" => "", "Continent" => "AN"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "VE", "Name" => "Venezuela", "Iso3" => "VEN", "Unicode" => "🇻🇪", "Dial" => "58", "currency_id" => "VEF", "Capital" => "Caracas", "Continent" => "SA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "PR", "Name" => "Puerto Rico", "Iso3" => "PRI", "Unicode" => "🇵🇷", "Dial" => "+1-787 and 1-939", "currency_id" => "USD", "Capital" => "San Juan", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "PS", "Name" => "Palestinian Territory", "Iso3" => "PSE", "Unicode" => "🇵🇸", "Dial" => "970", "currency_id" => "ILS", "Capital" => "East Jerusalem", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "PW", "Name" => "Palau", "Iso3" => "PLW", "Unicode" => "🇵🇼", "Dial" => "680", "currency_id" => "USD", "Capital" => "Melekeok", "Continent" => "OC"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "PT", "Name" => "Portugal", "Iso3" => "PRT", "Unicode" => "🇵🇹", "Dial" => "351", "currency_id" => "EUR", "Capital" => "Lisbon", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "SJ", "Name" => "Svalbard and Jan Mayen", "Iso3" => "SJM", "Unicode" => "🇸🇯", "Dial" => "47", "currency_id" => "NOK", "Capital" => "Longyearbyen", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "PY", "Name" => "Paraguay", "Iso3" => "PRY", "Unicode" => "🇵🇾", "Dial" => "595", "currency_id" => "PYG", "Capital" => "Asuncion", "Continent" => "SA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "IQ", "Name" => "Iraq", "Iso3" => "IRQ", "Unicode" => "🇮🇶", "Dial" => "964", "currency_id" => "IQD", "Capital" => "Baghdad", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "PA", "Name" => "Panama", "Iso3" => "PAN", "Unicode" => "🇵🇦", "Dial" => "507", "currency_id" => "PAB", "Capital" => "Panama City", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "PF", "Name" => "French Polynesia", "Iso3" => "PYF", "Unicode" => "🇵🇫", "Dial" => "689", "currency_id" => "XPF", "Capital" => "Papeete", "Continent" => "OC"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "PG", "Name" => "Papua New Guinea", "Iso3" => "PNG", "Unicode" => "🇵🇬", "Dial" => "675", "currency_id" => "PGK", "Capital" => "Port Moresby", "Continent" => "OC"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "PE", "Name" => "Peru", "Iso3" => "PER", "Unicode" => "🇵🇪", "Dial" => "51", "currency_id" => "PEN", "Capital" => "Lima", "Continent" => "SA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "PK", "Name" => "Pakistan", "Iso3" => "PAK", "Unicode" => "🇵🇰", "Dial" => "92", "currency_id" => "PKR", "Capital" => "Islamabad", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "PH", "Name" => "Philippines", "Iso3" => "PHL", "Unicode" => "🇵🇭", "Dial" => "63", "currency_id" => "PHP", "Capital" => "Manila", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "PN", "Name" => "Pitcairn", "Iso3" => "PCN", "Unicode" => "🇵🇳", "Dial" => "870", "currency_id" => "NZD", "Capital" => "Adamstown", "Continent" => "OC"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "PL", "Name" => "Poland", "Iso3" => "POL", "Unicode" => "🇵🇱", "Dial" => "48", "currency_id" => "PLN", "Capital" => "Warsaw", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "PM", "Name" => "Saint Pierre and Miquelon", "Iso3" => "SPM", "Unicode" => "🇵🇲", "Dial" => "508", "currency_id" => "EUR", "Capital" => "Saint-Pierre", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "ZM", "Name" => "Zambia", "Iso3" => "ZMB", "Unicode" => "🇿🇲", "Dial" => "260", "currency_id" => "ZMK", "Capital" => "Lusaka", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "EH", "Name" => "Western Sahara", "Iso3" => "ESH", "Unicode" => "🇪🇭", "Dial" => "212", "currency_id" => "MAD", "Capital" => "El-Aaiun", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "EE", "Name" => "Estonia", "Iso3" => "EST", "Unicode" => "🇪🇪", "Dial" => "372", "currency_id" => "EUR", "Capital" => "Tallinn", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "EG", "Name" => "Egypt", "Iso3" => "EGY", "Unicode" => "🇪🇬", "Dial" => "20", "currency_id" => "EGP", "Capital" => "Cairo", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "ZA", "Name" => "South Africa", "Iso3" => "ZAF", "Unicode" => "🇿🇦", "Dial" => "27", "currency_id" => "ZAR", "Capital" => "Pretoria", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "EC", "Name" => "Ecuador", "Iso3" => "ECU", "Unicode" => "🇪🇨", "Dial" => "593", "currency_id" => "USD", "Capital" => "Quito", "Continent" => "SA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "IT", "Name" => "Italy", "Iso3" => "ITA", "Unicode" => "🇮🇹", "Dial" => "39", "currency_id" => "EUR", "Capital" => "Rome", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "VN", "Name" => "Vietnam", "Iso3" => "VNM", "Unicode" => "🇻🇳", "Dial" => "84", "currency_id" => "VND", "Capital" => "Hanoi", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "SB", "Name" => "Solomon Islands", "Iso3" => "SLB", "Unicode" => "🇸🇧", "Dial" => "677", "currency_id" => "SBD", "Capital" => "Honiara", "Continent" => "OC"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "ET", "Name" => "Ethiopia", "Iso3" => "ETH", "Unicode" => "🇪🇹", "Dial" => "251", "currency_id" => "ETB", "Capital" => "Addis Ababa", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "SO", "Name" => "Somalia", "Iso3" => "SOM", "Unicode" => "🇸🇴", "Dial" => "252", "currency_id" => "SOS", "Capital" => "Mogadishu", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "ZW", "Name" => "Zimbabwe", "Iso3" => "ZWE", "Unicode" => "🇿🇼", "Dial" => "263", "currency_id" => "ZWL", "Capital" => "Harare", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "SA", "Name" => "Saudi Arabia", "Iso3" => "SAU", "Unicode" => "🇸🇦", "Dial" => "966", "currency_id" => "SAR", "Capital" => "Riyadh", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "ES", "Name" => "Spain", "Iso3" => "ESP", "Unicode" => "🇪🇸", "Dial" => "34", "currency_id" => "EUR", "Capital" => "Madrid", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "ER", "Name" => "Eritrea", "Iso3" => "ERI", "Unicode" => "🇪🇷", "Dial" => "291", "currency_id" => "ERN", "Capital" => "Asmara", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "ME", "Name" => "Montenegro", "Iso3" => "MNE", "Unicode" => "🇲🇪", "Dial" => "382", "currency_id" => "EUR", "Capital" => "Podgorica", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "MD", "Name" => "Moldova", "Iso3" => "MDA", "Unicode" => "🇲🇩", "Dial" => "373", "currency_id" => "MDL", "Capital" => "Chisinau", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "MG", "Name" => "Madagascar", "Iso3" => "MDG", "Unicode" => "🇲🇬", "Dial" => "261", "currency_id" => "MGA", "Capital" => "Antananarivo", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "MF", "Name" => "Saint Martin", "Iso3" => "MAF", "Unicode" => "🇲🇫", "Dial" => "590", "currency_id" => "EUR", "Capital" => "Marigot", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "MA", "Name" => "Morocco", "Iso3" => "MAR", "Unicode" => "🇲🇦", "Dial" => "212", "currency_id" => "MAD", "Capital" => "Rabat", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "MC", "Name" => "Monaco", "Iso3" => "MCO", "Unicode" => "🇲🇨", "Dial" => "377", "currency_id" => "EUR", "Capital" => "Monaco", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "UZ", "Name" => "Uzbekistan", "Iso3" => "UZB", "Unicode" => "🇺🇿", "Dial" => "998", "currency_id" => "UZS", "Capital" => "Tashkent", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "MM", "Name" => "Myanmar", "Iso3" => "MMR", "Unicode" => "🇲🇲", "Dial" => "95", "currency_id" => "MMK", "Capital" => "Nay Pyi Taw", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "ML", "Name" => "Mali", "Iso3" => "MLI", "Unicode" => "🇲🇱", "Dial" => "223", "currency_id" => "XOF", "Capital" => "Bamako", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "MO", "Name" => "Macao", "Iso3" => "MAC", "Unicode" => "🇲🇴", "Dial" => "853", "currency_id" => "MOP", "Capital" => "Macao", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "MN", "Name" => "Mongolia", "Iso3" => "MNG", "Unicode" => "🇲🇳", "Dial" => "976", "currency_id" => "MNT", "Capital" => "Ulan Bator", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "MH", "Name" => "Marshall Islands", "Iso3" => "MHL", "Unicode" => "🇲🇭", "Dial" => "692", "currency_id" => "USD", "Capital" => "Majuro", "Continent" => "OC"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "MK", "Name" => "Macedonia", "Iso3" => "MKD", "Unicode" => "🇲🇰", "Dial" => "389", "currency_id" => "MKD", "Capital" => "Skopje", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "MU", "Name" => "Mauritius", "Iso3" => "MUS", "Unicode" => "🇲🇺", "Dial" => "230", "currency_id" => "MUR", "Capital" => "Port Louis", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "MT", "Name" => "Malta", "Iso3" => "MLT", "Unicode" => "🇲🇹", "Dial" => "356", "currency_id" => "EUR", "Capital" => "Valletta", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "MW", "Name" => "Malawi", "Iso3" => "MWI", "Unicode" => "🇲🇼", "Dial" => "265", "currency_id" => "MWK", "Capital" => "Lilongwe", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "MV", "Name" => "Maldives", "Iso3" => "MDV", "Unicode" => "🇲🇻", "Dial" => "960", "currency_id" => "MVR", "Capital" => "Male", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "MQ", "Name" => "Martinique", "Iso3" => "MTQ", "Unicode" => "🇲🇶", "Dial" => "596", "currency_id" => "EUR", "Capital" => "Fort-de-France", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "MP", "Name" => "Northern Mariana Islands", "Iso3" => "MNP", "Unicode" => "🇲🇵", "Dial" => "+1-670", "currency_id" => "USD", "Capital" => "Saipan", "Continent" => "OC"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "MS", "Name" => "Montserrat", "Iso3" => "MSR", "Unicode" => "🇲🇸", "Dial" => "+1-664", "currency_id" => "XCD", "Capital" => "Plymouth", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "MR", "Name" => "Mauritania", "Iso3" => "MRT", "Unicode" => "🇲🇷", "Dial" => "222", "currency_id" => "MRO", "Capital" => "Nouakchott", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "IM", "Name" => "Isle of Man", "Iso3" => "IMN", "Unicode" => "🇮🇲", "Dial" => "+44-1624", "currency_id" => "GBP", "Capital" => "Douglas, Isle of Man", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "UG", "Name" => "Uganda", "Iso3" => "UGA", "Unicode" => "🇺🇬", "Dial" => "256", "currency_id" => "UGX", "Capital" => "Kampala", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "TZ", "Name" => "Tanzania", "Iso3" => "TZA", "Unicode" => "🇹🇿", "Dial" => "255", "currency_id" => "TZS", "Capital" => "Dodoma", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "MY", "Name" => "Malaysia", "Iso3" => "MYS", "Unicode" => "🇲🇾", "Dial" => "60", "currency_id" => "MYR", "Capital" => "Kuala Lumpur", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "MX", "Name" => "Mexico", "Iso3" => "MEX", "Unicode" => "🇲🇽", "Dial" => "52", "currency_id" => "MXN", "Capital" => "Mexico City", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "IL", "Name" => "Israel", "Iso3" => "ISR", "Unicode" => "🇮🇱", "Dial" => "972", "currency_id" => "ILS", "Capital" => "Jerusalem", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "FR", "Name" => "France", "Iso3" => "FRA", "Unicode" => "🇫🇷", "Dial" => "33", "currency_id" => "EUR", "Capital" => "Paris", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "IO", "Name" => "British Indian Ocean Territory", "Iso3" => "IOT", "Unicode" => "🇮🇴", "Dial" => "246", "currency_id" => "USD", "Capital" => "Diego Garcia", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "SH", "Name" => "Saint Helena", "Iso3" => "SHN", "Unicode" => "🇸🇭", "Dial" => "290", "currency_id" => "SHP", "Capital" => "Jamestown", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "FI", "Name" => "Finland", "Iso3" => "FIN", "Unicode" => "🇫🇮", "Dial" => "358", "currency_id" => "EUR", "Capital" => "Helsinki", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "FJ", "Name" => "Fiji", "Iso3" => "FJI", "Unicode" => "🇫🇯", "Dial" => "679", "currency_id" => "FJD", "Capital" => "Suva", "Continent" => "OC"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "FK", "Name" => "Falkland Islands", "Iso3" => "FLK", "Unicode" => "🇫🇰", "Dial" => "500", "currency_id" => "FKP", "Capital" => "Stanley", "Continent" => "SA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "FM", "Name" => "Micronesia", "Iso3" => "FSM", "Unicode" => "🇫🇲", "Dial" => "691", "currency_id" => "USD", "Capital" => "Palikir", "Continent" => "OC"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "FO", "Name" => "Faroe Islands", "Iso3" => "FRO", "Unicode" => "🇫🇴", "Dial" => "298", "currency_id" => "DKK", "Capital" => "Torshavn", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "NI", "Name" => "Nicaragua", "Iso3" => "NIC", "Unicode" => "🇳🇮", "Dial" => "505", "currency_id" => "NIO", "Capital" => "Managua", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "NL", "Name" => "Netherlands", "Iso3" => "NLD", "Unicode" => "🇳🇱", "Dial" => "31", "currency_id" => "EUR", "Capital" => "Amsterdam", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "NO", "Name" => "Norway", "Iso3" => "NOR", "Unicode" => "🇳🇴", "Dial" => "47", "currency_id" => "NOK", "Capital" => "Oslo", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "NA", "Name" => "Namibia", "Iso3" => "NAM", "Unicode" => "🇳🇦", "Dial" => "264", "currency_id" => "NAD", "Capital" => "Windhoek", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "VU", "Name" => "Vanuatu", "Iso3" => "VUT", "Unicode" => "🇻🇺", "Dial" => "678", "currency_id" => "VUV", "Capital" => "Port Vila", "Continent" => "OC"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "NC", "Name" => "New Caledonia", "Iso3" => "NCL", "Unicode" => "🇳🇨", "Dial" => "687", "currency_id" => "XPF", "Capital" => "Noumea", "Continent" => "OC"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "NE", "Name" => "Niger", "Iso3" => "NER", "Unicode" => "🇳🇪", "Dial" => "227", "currency_id" => "XOF", "Capital" => "Niamey", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "NF", "Name" => "Norfolk Island", "Iso3" => "NFK", "Unicode" => "🇳🇫", "Dial" => "672", "currency_id" => "AUD", "Capital" => "Kingston", "Continent" => "OC"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "NG", "Name" => "Nigeria", "Iso3" => "NGA", "Unicode" => "🇳🇬", "Dial" => "234", "currency_id" => "NGN", "Capital" => "Abuja", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "NZ", "Name" => "New Zealand", "Iso3" => "NZL", "Unicode" => "🇳🇿", "Dial" => "64", "currency_id" => "NZD", "Capital" => "Wellington", "Continent" => "OC"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "NP", "Name" => "Nepal", "Iso3" => "NPL", "Unicode" => "🇳🇵", "Dial" => "977", "currency_id" => "NPR", "Capital" => "Kathmandu", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "NR", "Name" => "Nauru", "Iso3" => "NRU", "Unicode" => "🇳🇷", "Dial" => "674", "currency_id" => "AUD", "Capital" => "Yaren", "Continent" => "OC"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "NU", "Name" => "Niue", "Iso3" => "NIU", "Unicode" => "🇳🇺", "Dial" => "683", "currency_id" => "NZD", "Capital" => "Alofi", "Continent" => "OC"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "CK", "Name" => "Cook Islands", "Iso3" => "COK", "Unicode" => "🇨🇰", "Dial" => "682", "currency_id" => "NZD", "Capital" => "Avarua", "Continent" => "OC"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "XK", "Name" => "Kosovo", "Iso3" => "XKX", "Unicode" => "🇽🇰", "Dial" => "", "currency_id" => "EUR", "Capital" => "Pristina", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "CI", "Name" => "Ivory Coast", "Iso3" => "CIV", "Unicode" => "🇨🇮", "Dial" => "225", "currency_id" => "XOF", "Capital" => "Yamoussoukro", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "CH", "Name" => "Switzerland", "Iso3" => "CHE", "Unicode" => "🇨🇭", "Dial" => "41", "currency_id" => "CHF", "Capital" => "Berne", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "CO", "Name" => "Colombia", "Iso3" => "COL", "Unicode" => "🇨🇴", "Dial" => "57", "currency_id" => "COP", "Capital" => "Bogota", "Continent" => "SA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "CN", "Name" => "China", "Iso3" => "CHN", "Unicode" => "🇨🇳", "Dial" => "86", "currency_id" => "CNY", "Capital" => "Beijing", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "CM", "Name" => "Cameroon", "Iso3" => "CMR", "Unicode" => "🇨🇲", "Dial" => "237", "currency_id" => "XAF", "Capital" => "Yaounde", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "CL", "Name" => "Chile", "Iso3" => "CHL", "Unicode" => "🇨🇱", "Dial" => "56", "currency_id" => "CLP", "Capital" => "Santiago", "Continent" => "SA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "CC", "Name" => "Cocos Islands", "Iso3" => "CCK", "Unicode" => "🇨🇨", "Dial" => "61", "currency_id" => "AUD", "Capital" => "West Island", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "CA", "Name" => "Canada", "Iso3" => "CAN", "Unicode" => "🇨🇦", "Dial" => "1", "currency_id" => "CAD", "Capital" => "Ottawa", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "CG", "Name" => "Republic of the Congo", "Iso3" => "COG", "Unicode" => "🇨🇬", "Dial" => "242", "currency_id" => "XAF", "Capital" => "Brazzaville", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "CF", "Name" => "Central African Republic", "Iso3" => "CAF", "Unicode" => "🇨🇫", "Dial" => "236", "currency_id" => "XAF", "Capital" => "Bangui", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "CD", "Name" => "Democratic Republic of the Congo", "Iso3" => "COD", "Unicode" => "🇨🇩", "Dial" => "243", "currency_id" => "CDF", "Capital" => "Kinshasa", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "CZ", "Name" => "Czech Republic", "Iso3" => "CZE", "Unicode" => "🇨🇿", "Dial" => "420", "currency_id" => "CZK", "Capital" => "Prague", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "CY", "Name" => "Cyprus", "Iso3" => "CYP", "Unicode" => "🇨🇾", "Dial" => "357", "currency_id" => "EUR", "Capital" => "Nicosia", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "CX", "Name" => "Christmas Island", "Iso3" => "CXR", "Unicode" => "🇨🇽", "Dial" => "61", "currency_id" => "AUD", "Capital" => "Flying Fish Cove", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "CR", "Name" => "Costa Rica", "Iso3" => "CRI", "Unicode" => "🇨🇷", "Dial" => "506", "currency_id" => "CRC", "Capital" => "San Jose", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "CW", "Name" => "Curacao", "Iso3" => "CUW", "Unicode" => "🇨🇼", "Dial" => "599", "currency_id" => "ANG", "Capital" => " Willemstad", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "CV", "Name" => "Cape Verde", "Iso3" => "CPV", "Unicode" => "🇨🇻", "Dial" => "238", "currency_id" => "CVE", "Capital" => "Praia", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "CU", "Name" => "Cuba", "Iso3" => "CUB", "Unicode" => "🇨🇺", "Dial" => "53", "currency_id" => "CUP", "Capital" => "Havana", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "SZ", "Name" => "Swaziland", "Iso3" => "SWZ", "Unicode" => "🇸🇿", "Dial" => "268", "currency_id" => "SZL", "Capital" => "Mbabane", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "SY", "Name" => "Syria", "Iso3" => "SYR", "Unicode" => "🇸🇾", "Dial" => "963", "currency_id" => "SYP", "Capital" => "Damascus", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "SX", "Name" => "Sint Maarten", "Iso3" => "SXM", "Unicode" => "🇸🇽", "Dial" => "599", "currency_id" => "ANG", "Capital" => "Philipsburg", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "KG", "Name" => "Kyrgyzstan", "Iso3" => "KGZ", "Unicode" => "🇰🇬", "Dial" => "996", "currency_id" => "KGS", "Capital" => "Bishkek", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "KE", "Name" => "Kenya", "Iso3" => "KEN", "Unicode" => "🇰🇪", "Dial" => "254", "currency_id" => "KES", "Capital" => "Nairobi", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "SS", "Name" => "South Sudan", "Iso3" => "SSD", "Unicode" => "🇸🇸", "Dial" => "211", "currency_id" => "SSP", "Capital" => "Juba", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "SR", "Name" => "Suriname", "Iso3" => "SUR", "Unicode" => "🇸🇷", "Dial" => "597", "currency_id" => "SRD", "Capital" => "Paramaribo", "Continent" => "SA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "KI", "Name" => "Kiribati", "Iso3" => "KIR", "Unicode" => "🇰🇮", "Dial" => "686", "currency_id" => "AUD", "Capital" => "Tarawa", "Continent" => "OC"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "KH", "Name" => "Cambodia", "Iso3" => "KHM", "Unicode" => "🇰🇭", "Dial" => "855", "currency_id" => "KHR", "Capital" => "Phnom Penh", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "KN", "Name" => "Saint Kitts and Nevis", "Iso3" => "KNA", "Unicode" => "🇰🇳", "Dial" => "+1-869", "currency_id" => "XCD", "Capital" => "Basseterre", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "KM", "Name" => "Comoros", "Iso3" => "COM", "Unicode" => "🇰🇲", "Dial" => "269", "currency_id" => "KMF", "Capital" => "Moroni", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "ST", "Name" => "Sao Tome and Principe", "Iso3" => "STP", "Unicode" => "🇸🇹", "Dial" => "239", "currency_id" => "STD", "Capital" => "Sao Tome", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "SK", "Name" => "Slovakia", "Iso3" => "SVK", "Unicode" => "🇸🇰", "Dial" => "421", "currency_id" => "EUR", "Capital" => "Bratislava", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "KR", "Name" => "South Korea", "Iso3" => "KOR", "Unicode" => "🇰🇷", "Dial" => "82", "currency_id" => "KRW", "Capital" => "Seoul", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "SI", "Name" => "Slovenia", "Iso3" => "SVN", "Unicode" => "🇸🇮", "Dial" => "386", "currency_id" => "EUR", "Capital" => "Ljubljana", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "KP", "Name" => "North Korea", "Iso3" => "PRK", "Unicode" => "🇰🇵", "Dial" => "850", "currency_id" => "KPW", "Capital" => "Pyongyang", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "KW", "Name" => "Kuwait", "Iso3" => "KWT", "Unicode" => "🇰🇼", "Dial" => "965", "currency_id" => "KWD", "Capital" => "Kuwait City", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "SN", "Name" => "Senegal", "Iso3" => "SEN", "Unicode" => "🇸🇳", "Dial" => "221", "currency_id" => "XOF", "Capital" => "Dakar", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "SM", "Name" => "San Marino", "Iso3" => "SMR", "Unicode" => "🇸🇲", "Dial" => "378", "currency_id" => "EUR", "Capital" => "San Marino", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "SL", "Name" => "Sierra Leone", "Iso3" => "SLE", "Unicode" => "🇸🇱", "Dial" => "232", "currency_id" => "SLL", "Capital" => "Freetown", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "SC", "Name" => "Seychelles", "Iso3" => "SYC", "Unicode" => "🇸🇨", "Dial" => "248", "currency_id" => "SCR", "Capital" => "Victoria", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "KZ", "Name" => "Kazakhstan", "Iso3" => "KAZ", "Unicode" => "🇰🇿", "Dial" => "7", "currency_id" => "KZT", "Capital" => "Astana", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "KY", "Name" => "Cayman Islands", "Iso3" => "CYM", "Unicode" => "🇰🇾", "Dial" => "+1-345", "currency_id" => "KYD", "Capital" => "George Town", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "SG", "Name" => "Singapore", "Iso3" => "SGP", "Unicode" => "🇸🇬", "Dial" => "65", "currency_id" => "SGD", "Capital" => "Singapur", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "SE", "Name" => "Sweden", "Iso3" => "SWE", "Unicode" => "🇸🇪", "Dial" => "46", "currency_id" => "SEK", "Capital" => "Stockholm", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "SD", "Name" => "Sudan", "Iso3" => "SDN", "Unicode" => "🇸🇩", "Dial" => "249", "currency_id" => "SDG", "Capital" => "Khartoum", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "DO", "Name" => "Dominican Republic", "Iso3" => "DOM", "Unicode" => "🇩🇴", "Dial" => "+1-809 and 1-829", "currency_id" => "DOP", "Capital" => "Santo Domingo", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "DM", "Name" => "Dominica", "Iso3" => "DMA", "Unicode" => "🇩🇲", "Dial" => "+1-767", "currency_id" => "XCD", "Capital" => "Roseau", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "DJ", "Name" => "Djibouti", "Iso3" => "DJI", "Unicode" => "🇩🇯", "Dial" => "253", "currency_id" => "DJF", "Capital" => "Djibouti", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "DK", "Name" => "Denmark", "Iso3" => "DNK", "Unicode" => "🇩🇰", "Dial" => "45", "currency_id" => "DKK", "Capital" => "Copenhagen", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "VG", "Name" => "British Virgin Islands", "Iso3" => "VGB", "Unicode" => "🇻🇬", "Dial" => "+1-284", "currency_id" => "USD", "Capital" => "Road Town", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "DE", "Name" => "Germany", "Iso3" => "DEU", "Unicode" => "🇩🇪", "Dial" => "49", "currency_id" => "EUR", "Capital" => "Berlin", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "YE", "Name" => "Yemen", "Iso3" => "YEM", "Unicode" => "🇾🇪", "Dial" => "967", "currency_id" => "YER", "Capital" => "Sanaa", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "DZ", "Name" => "Algeria", "Iso3" => "DZA", "Unicode" => "🇩🇿", "Dial" => "213", "currency_id" => "DZD", "Capital" => "Algiers", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "US", "Name" => "United States", "Iso3" => "USA", "Unicode" => "🇺🇸", "Dial" => "1", "currency_id" => "USD", "Capital" => "Washington", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "UY", "Name" => "Uruguay", "Iso3" => "URY", "Unicode" => "🇺🇾", "Dial" => "598", "currency_id" => "UYU", "Capital" => "Montevideo", "Continent" => "SA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "YT", "Name" => "Mayotte", "Iso3" => "MYT", "Unicode" => "🇾🇹", "Dial" => "262", "currency_id" => "EUR", "Capital" => "Mamoudzou", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "UM", "Name" => "United States Minor Outlying Islands", "Iso3" => "UMI", "Unicode" => "🇺🇲", "Dial" => "1", "currency_id" => "USD", "Capital" => "", "Continent" => "OC"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "LB", "Name" => "Lebanon", "Iso3" => "LBN", "Unicode" => "🇱🇧", "Dial" => "961", "currency_id" => "LBP", "Capital" => "Beirut", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "LC", "Name" => "Saint Lucia", "Iso3" => "LCA", "Unicode" => "🇱🇨", "Dial" => "+1-758", "currency_id" => "XCD", "Capital" => "Castries", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "LA", "Name" => "Laos", "Iso3" => "LAO", "Unicode" => "🇱🇦", "Dial" => "856", "currency_id" => "LAK", "Capital" => "Vientiane", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "TV", "Name" => "Tuvalu", "Iso3" => "TUV", "Unicode" => "🇹🇻", "Dial" => "688", "currency_id" => "AUD", "Capital" => "Funafuti", "Continent" => "OC"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "TW", "Name" => "Taiwan", "Iso3" => "TWN", "Unicode" => "🇹🇼", "Dial" => "886", "currency_id" => "TWD", "Capital" => "Taipei", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "TT", "Name" => "Trinidad and Tobago", "Iso3" => "TTO", "Unicode" => "🇹🇹", "Dial" => "+1-868", "currency_id" => "TTD", "Capital" => "Port of Spain", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "TR", "Name" => "Turkey", "Iso3" => "TUR", "Unicode" => "🇹🇷", "Dial" => "90", "currency_id" => "TRY", "Capital" => "Ankara", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "LK", "Name" => "Sri Lanka", "Iso3" => "LKA", "Unicode" => "🇱🇰", "Dial" => "94", "currency_id" => "LKR", "Capital" => "Colombo", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "LI", "Name" => "Liechtenstein", "Iso3" => "LIE", "Unicode" => "🇱🇮", "Dial" => "423", "currency_id" => "CHF", "Capital" => "Vaduz", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "LV", "Name" => "Latvia", "Iso3" => "LVA", "Unicode" => "🇱🇻", "Dial" => "371", "currency_id" => "EUR", "Capital" => "Riga", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "TO", "Name" => "Tonga", "Iso3" => "TON", "Unicode" => "🇹🇴", "Dial" => "676", "currency_id" => "TOP", "Capital" => "Nuku'alofa", "Continent" => "OC"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "LT", "Name" => "Lithuania", "Iso3" => "LTU", "Unicode" => "🇱🇹", "Dial" => "370", "currency_id" => "LTL", "Capital" => "Vilnius", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "LU", "Name" => "Luxembourg", "Iso3" => "LUX", "Unicode" => "🇱🇺", "Dial" => "352", "currency_id" => "EUR", "Capital" => "Luxembourg", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "LR", "Name" => "Liberia", "Iso3" => "LBR", "Unicode" => "🇱🇷", "Dial" => "231", "currency_id" => "LRD", "Capital" => "Monrovia", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "LS", "Name" => "Lesotho", "Iso3" => "LSO", "Unicode" => "🇱🇸", "Dial" => "266", "currency_id" => "LSL", "Capital" => "Maseru", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "TH", "Name" => "Thailand", "Iso3" => "THA", "Unicode" => "🇹🇭", "Dial" => "66", "currency_id" => "THB", "Capital" => "Bangkok", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "TF", "Name" => "French Southern Territories", "Iso3" => "ATF", "Unicode" => "🇹🇫", "Dial" => "", "currency_id" => "EUR", "Capital" => "Port-aux-Francais", "Continent" => "AN"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "TG", "Name" => "Togo", "Iso3" => "TGO", "Unicode" => "🇹🇬", "Dial" => "228", "currency_id" => "XOF", "Capital" => "Lome", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "TD", "Name" => "Chad", "Iso3" => "TCD", "Unicode" => "🇹🇩", "Dial" => "235", "currency_id" => "XAF", "Capital" => "N'Djamena", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "TC", "Name" => "Turks and Caicos Islands", "Iso3" => "TCA", "Unicode" => "🇹🇨", "Dial" => "+1-649", "currency_id" => "USD", "Capital" => "Cockburn Town", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "LY", "Name" => "Libya", "Iso3" => "LBY", "Unicode" => "🇱🇾", "Dial" => "218", "currency_id" => "LYD", "Capital" => "Tripolis", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "VA", "Name" => "Vatican", "Iso3" => "VAT", "Unicode" => "🇻🇦", "Dial" => "379", "currency_id" => "EUR", "Capital" => "Vatican City", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "VC", "Name" => "Saint Vincent and the Grenadines", "Iso3" => "VCT", "Unicode" => "🇻🇨", "Dial" => "+1-784", "currency_id" => "XCD", "Capital" => "Kingstown", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "AE", "Name" => "United Arab Emirates", "Iso3" => "ARE", "Unicode" => "🇦🇪", "Dial" => "971", "currency_id" => "AED", "Capital" => "Abu Dhabi", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "AD", "Name" => "Andorra", "Iso3" => "AND", "Unicode" => "🇦🇩", "Dial" => "376", "currency_id" => "EUR", "Capital" => "Andorra la Vella", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "AG", "Name" => "Antigua and Barbuda", "Iso3" => "ATG", "Unicode" => "🇦🇬", "Dial" => "+1-268", "currency_id" => "XCD", "Capital" => "St. John's", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "AF", "Name" => "Afghanistan", "Iso3" => "AFG", "Unicode" => "🇦🇫", "Dial" => "93", "currency_id" => "AFN", "Capital" => "Kabul", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "AI", "Name" => "Anguilla", "Iso3" => "AIA", "Unicode" => "🇦🇮", "Dial" => "+1-264", "currency_id" => "XCD", "Capital" => "The Valley", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "VI", "Name" => "U.S. Virgin Islands", "Iso3" => "VIR", "Unicode" => "🇻🇮", "Dial" => "+1-340", "currency_id" => "USD", "Capital" => "Charlotte Amalie", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "IS", "Name" => "Iceland", "Iso3" => "ISL", "Unicode" => "🇮🇸", "Dial" => "354", "currency_id" => "ISK", "Capital" => "Reykjavik", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "IR", "Name" => "Iran", "Iso3" => "IRN", "Unicode" => "🇮🇷", "Dial" => "98", "currency_id" => "IRR", "Capital" => "Tehran", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "AM", "Name" => "Armenia", "Iso3" => "ARM", "Unicode" => "🇦🇲", "Dial" => "374", "currency_id" => "AMD", "Capital" => "Yerevan", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "AL", "Name" => "Albania", "Iso3" => "ALB", "Unicode" => "🇦🇱", "Dial" => "355", "currency_id" => "ALL", "Capital" => "Tirana", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "AO", "Name" => "Angola", "Iso3" => "AGO", "Unicode" => "🇦🇴", "Dial" => "244", "currency_id" => "AOA", "Capital" => "Luanda", "Continent" => "AF"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "AQ", "Name" => "Antarctica", "Iso3" => "ATA", "Unicode" => "🇦🇶", "Dial" => "", "currency_id" => "", "Capital" => "", "Continent" => "AN"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "AS", "Name" => "American Samoa", "Iso3" => "ASM", "Unicode" => "🇦🇸", "Dial" => "+1-684", "currency_id" => "USD", "Capital" => "Pago Pago", "Continent" => "OC"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "AR", "Name" => "Argentina", "Iso3" => "ARG", "Unicode" => "🇦🇷", "Dial" => "54", "currency_id" => "ARS", "Capital" => "Buenos Aires", "Continent" => "SA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "AU", "Name" => "Australia", "Iso3" => "AUS", "Unicode" => "🇦🇺", "Dial" => "61", "currency_id" => "AUD", "Capital" => "Canberra", "Continent" => "OC"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "AT", "Name" => "Austria", "Iso3" => "AUT", "Unicode" => "🇦🇹", "Dial" => "43", "currency_id" => "EUR", "Capital" => "Vienna", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "AW", "Name" => "Aruba", "Iso3" => "ABW", "Unicode" => "🇦🇼", "Dial" => "297", "currency_id" => "AWG", "Capital" => "Oranjestad", "Continent" => "NA"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "IN", "Name" => "India", "Iso3" => "IND", "Unicode" => "🇮🇳", "Dial" => "91", "currency_id" => "INR", "Capital" => "New Delhi", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "AX", "Name" => "Aland Islands", "Iso3" => "ALA", "Unicode" => "🇦🇽", "Dial" => "+358-18", "currency_id" => "EUR", "Capital" => "Mariehamn", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "AZ", "Name" => "Azerbaijan", "Iso3" => "AZE", "Unicode" => "🇦🇿", "Dial" => "994", "currency_id" => "AZN", "Capital" => "Baku", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "IE", "Name" => "Ireland", "Iso3" => "IRL", "Unicode" => "🇮🇪", "Dial" => "353", "currency_id" => "EUR", "Capital" => "Dublin", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "ID", "Name" => "Indonesia", "Iso3" => "IDN", "Unicode" => "🇮🇩", "Dial" => "62", "currency_id" => "IDR", "Capital" => "Jakarta", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "UA", "Name" => "Ukraine", "Iso3" => "UKR", "Unicode" => "🇺🇦", "Dial" => "380", "currency_id" => "UAH", "Capital" => "Kiev", "Continent" => "EU"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "QA", "Name" => "Qatar", "Iso3" => "QAT", "Unicode" => "🇶🇦", "Dial" => "974", "currency_id" => "QAR", "Capital" => "Doha", "Continent" => "AS"], [
            "countries_created_at" => Carbon::now()->format('Y-m-d H:i:s'), "countries_updated_at" => Carbon::now()->format('Y-m-d H:i:s'), "country_id" => (string) Str::uuid(), "Iso2" => "MZ", "Name" => "Mozambique", "Iso3" => "MOZ", "Unicode" => "🇲🇿", "Dial" => "258", "currency_id" => "MZN", "Capital" => "Maputo", "Continent" => "AF"]]);
            DB::statement('SET FOREIGN_KEY_CHECKS=1');
    }
}
