<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Countries extends Model
{
    public $incrementing = false;
    protected $table='countries';
    protected $keyType = 'string';
    protected $fillable = [
        'uuid', 'Name'
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($Countries) {
            $Countries->uuid = (string) Str::uuid();
        });
    }

    public function getIncrementing()
    {
        return false;
    }

    public function getKeyType()
    {
        return 'string';
    }
}
